module Ros.Tests.Program

[<EntryPoint>]
let main _ =
    ArchitectureTests.tests
    @ CliHarnessTests.tests
    @ ArtifactTests.tests
    @ PersistenceTests.tests
    @ GitTests.tests
    @ WorkTests.tests
    @ EnvelopeReconciliationTests.tests
    @ WorkPlanTests.tests
    @ BacklogTests.tests
    @ TelemetryTests.tests
    @ TelemetryResolutionTests.tests
    @ ChangeSummaryTests.tests
    @ PathFilterTests.tests
    @ WorkAttributionTests.tests
    @ QueueValidationTests.tests
    @ QueuePresentationTests.tests
    @ BacklogTransitionEffectTests.tests
    @ WorkCaptureTests.tests
    @ WorkCaptureEffectTests.tests
    @ WorkUpdateTests.tests
    @ WorkUpdateEffectTests.tests
    @ WorkAttachmentTests.tests
    @ WorkAttachmentEffectTests.tests
    @ TelemetryIdentityTests.tests
    @ WorkContextEffectTests.tests
    @ WorkContextViewTests.tests
    @ WorkListViewTests.tests
    @ TelemetryValidationTests.tests
    @ FindingContractTests.tests
    @ TelemetryQueryTests.tests
    @ TelemetryLifecycleTests.tests
    @ TelemetrySummaryTests.tests
    @ TutelaTelemetryTests.tests
    @ TelemetryFinalizeTargetTests.tests
    @ TelemetryRecordMetricTests.tests
    @ TelemetryIngestTests.tests
    @ TelemetryIngestOpenAICodexTests.tests
    @ TelemetryIngestHookTests.tests
    @ TelemetryIngestClaudeStatuslineTests.tests
    @ TelemetryIngestOtelTests.tests
    @ TelemetryIngestClaudeSessionTests.tests
    @ TelemetryClassifyTests.tests
    @ TelemetryStartTests.tests
    @ StepTelemetryTests.tests
    @ AdapterContractTests.tests
    @ AdapterCallEffectTests.tests
    @ AdapterPublishEffectTests.tests
    @ LifecycleTests.tests
    @ FoundationsTests.tests
    @ OrdoObservationTests.tests
    @ ProvenanceTests.tests
    @ ProvenanceEffectTests.tests
    @ WorkReconciliationTests.tests
    @ WorkReconciliationEffectTests.tests
    @ ImplementationLanguagePolicyTests.tests
    @ WebInterfaceTests.tests
    @ HubTests.tests
    @ WorkDecisionCliTests.tests
    @ WorkTelemetryCliTests.tests
    @ WorkGitPathsCliTests.tests
    @ WorkValidateCliTests.tests
    @ WorkBacklogCliTests.tests
    @ WorkLifecycleCliTests.tests
    @ WorkViewCliTests.tests
    @ StatusValidateCliTests.tests
    @ GitArtifactCliTests.tests
    @ TelemetryCliTests.tests
    @ TelemetryAdapterCliTests.tests
    @ AdapterCliTests.tests
    @ ProvenanceCliTests.tests
    @ LifecycleCliTests.tests
    @ EchelonDoctorTests.tests
    @ InstalledRepositoryTests.tests
    @ RemoteProtocolTests.tests
    @ RemoteIdentityTests.tests
    @ RemoteExecutionTests.tests
    @ RemoteExecuteCliTests.tests
    @ RemotePersistScriptTests.tests
    @ PraxisBootstrapScriptTests.tests
    @ TelemetryStepsUsageTests.tests
    @ PraxisNamingTests.tests
    @ CheckpointDomainTests.tests
    @ GitDurabilityTests.tests
    @ CheckpointPersistenceTests.tests
    @ CheckpointCliTests.tests
    @ CheckpointGuardTests.tests
    @ ContinuationCliTests.tests
    @ TelemetrySegmentationTests.tests
    @ RecoveryProofTests.tests
    @ ExecutionGovernanceTests.tests
    @ InstallationRegistrationTests.tests
    @ CommitOwnershipTests.tests
    @ WorkAbandonTests.tests
    @ PlanningTests.tests
    @ PlanningCliTests.tests
    @ PlanningSessionEvidenceTests.tests
    @ GroupingTests.tests
    @ PremergeCommandSurfaceTests.tests
    @ PremergeRemoteTests.tests
    @ PremergeRemoteScriptTests.tests
    @ PremergeReleaseTests.tests
    @ PostmergeReconciliationTests.tests
    @ WorkGroupTests.tests
    @ TelemetryCostUnitTests.tests
    @ ValueAnchorTests.tests
    |> TestRunner.run
