module Praxis.Tests.Program

/// `--suite browser` runs the browser suite (headless Chrome, DF-ROS-2026-A058);
/// with no argument, every other test runs. CI runs both.
[<EntryPoint>]
let main argv =
  match argv with
  | [| "--suite"; "browser" |] -> TestRunner.run BrowserTests.tests
  | [||] ->
    ArchitectureTests.tests
    @ CliHarnessTests.tests
    @ ArtifactTests.tests
    @ PersistenceTests.tests
    @ GitTests.tests
    @ UpstreamSyncTests.tests
    @ WorkTests.tests
    @ EnvelopeReconciliationTests.tests
    @ WorkPlanTests.tests
    @ BacklogTests.tests
    @ TelemetryTests.tests
    @ TelemetryResolutionTests.tests
    @ ChangeSummaryTests.tests
    @ PathFilterTests.tests
    @ WorkAttributionTests.tests
    @ QueueValidationTests.tests
    @ QueuePresentationTests.tests
    @ BacklogTransitionEffectTests.tests
    @ WorkCaptureTests.tests
    @ ConsumerLinksTests.tests
    @ WorkCaptureEffectTests.tests
    @ WorkUpdateTests.tests
    @ WorkUpdateEffectTests.tests
    @ WorkAttachmentTests.tests
    @ WorkAttachmentEffectTests.tests
    @ TelemetryIdentityTests.tests
    @ WorkContextEffectTests.tests
    @ WorkContextViewTests.tests
    @ WorkListViewTests.tests
    @ TelemetryValidationTests.tests
    @ FindingContractTests.tests
    @ TelemetryQueryTests.tests
    @ TelemetryLifecycleTests.tests
    @ TelemetrySummaryTests.tests
    @ TutelaTelemetryTests.tests
    @ TutelaMetricsTests.tests
    @ TelemetryFinalizeTargetTests.tests
    @ TelemetryRecordMetricTests.tests
    @ TelemetryIngestTests.tests
    @ TelemetryIngestOpenAICodexTests.tests
    @ TelemetryIngestHookTests.tests
    @ TelemetryIngestClaudeStatuslineTests.tests
    @ TelemetryIngestOtelTests.tests
    @ TelemetryIngestClaudeSessionTests.tests
    @ TelemetryClassifyTests.tests
    @ TelemetryStartTests.tests
    @ StepTelemetryTests.tests
    @ AdapterContractTests.tests
    @ AdapterCallEffectTests.tests
    @ AdapterPublishEffectTests.tests
    @ LifecycleTests.tests
    @ FoundationsTests.tests
    @ RoutingFoundationsTests.tests
    @ RoutingFoundationsTests.limenTests
    @ UrlStateTests.tests
    @ OrdoObservationTests.tests
    @ ProvenanceTests.tests
    @ ProvenanceEffectTests.tests
    @ WorkReconciliationTests.tests
    @ WorkReconciliationEffectTests.tests
    @ ImplementationLanguagePolicyTests.tests
    @ RequirementCitationTests.tests
    @ InputInboxTests.tests
    @ WebInterfaceTests.tests
    @ HubTests.tests
    @ WorkDecisionCliTests.tests
    @ WorkTelemetryCliTests.tests
    @ WorkGitPathsCliTests.tests
    @ WorkValidateCliTests.tests
    @ WorkBacklogCliTests.tests
    @ BacklogReidentificationTests.tests
    @ StatusTableCitationTests.tests
    @ WorkLifecycleCliTests.tests
    @ WorkViewCliTests.tests
    @ StatusValidateCliTests.tests
    @ GitArtifactCliTests.tests
    @ TelemetryCliTests.tests
    @ TelemetryAdapterCliTests.tests
    @ AdapterCliTests.tests
    @ ProvenanceCliTests.tests
    @ LifecycleCliTests.tests
    @ EchelonDoctorTests.tests
    @ InstalledRepositoryTests.tests
    @ RemoteProtocolTests.tests
    @ RemoteIdentityTests.tests
    @ RemoteExecutionTests.tests
    @ RemoteExecuteCliTests.tests
    @ RemotePersistScriptTests.tests
    @ PraxisBootstrapScriptTests.tests
    @ TelemetryStepsUsageTests.tests
    @ PraxisNamingTests.tests
    @ CheckpointDomainTests.tests
    @ GitDurabilityTests.tests
    @ CheckpointPersistenceTests.tests
    @ CheckpointCliTests.tests
    @ CheckpointGuardTests.tests
    @ ContinuationCliTests.tests
    @ TelemetrySegmentationTests.tests
    @ RecoveryProofTests.tests
    @ ExecutionGovernanceTests.tests
    @ ExecutionRuntimeTests.tests
    @ ExecutionBindingTests.tests
    @ WebExecutionTests.tests
    @ InstallationRegistrationTests.tests
    @ CommitOwnershipTests.tests
    @ WorkAbandonTests.tests
    @ PlanningTests.tests
    @ PlanningCapacityTests.tests
    @ PacingTests.tests
    @ PacingSafetyTests.tests
    @ PacingHardeningTests.tests
    @ CliBoundaryRatchetTests.tests
    @ PlanningCliTests.tests
    @ PlanningSessionEvidenceTests.tests
    @ PlanningEvidenceTests.tests
    @ GroupingTests.tests
    @ PremergeCommandSurfaceTests.tests
    @ PremergeRemoteTests.tests
    @ PremergeRemoteScriptTests.tests
    @ PremergeReleaseTests.tests
    @ PostmergeReconciliationTests.tests
    @ WorkGroupTests.tests
    @ GroupGateTests.tests
    @ EcirGateTests.tests
    @ EcirPreflightTests.tests
    @ EcirApprovalTests.tests
    @ EcirHostTests.tests
    @ LocalAgentHandoffTests.tests
    @ LocalDispatchJournalTests.tests
    @ ExecuteGroupTests.tests
    @ GroupMeasurementTests.tests
    @ InternalNamingGuardTests.tests
    @ InternalNamingTests.tests
    @ TelemetryCostUnitTests.tests
    @ QualityEvidenceTests.tests
    @ FormaPresentationTests.tests
    @ AegisBoundaryTests.tests
    @ IdentityTests.tests
    @ CompletionObligationsTests.tests
    @ ProvenanceAcknowledgementTests.tests
    @ UrlEnhancementTests.tests
    |> TestRunner.run
  | other -> eprintfn "unknown arguments: %s (expected none, or --suite browser)" (String.concat " " other); 2
