<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ros.Domain/Ros.Domain.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
  </ItemGroup>
</Project>
