<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ros.Integration/Ros.Integration.fsproj" />
    <ProjectReference Include="../Ros.ProjectAdministration/Ros.ProjectAdministration.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="ActivityStore.fs" />
    <Compile Include="OutboxStore.fs" />
  </ItemGroup>
</Project>
