#!/usr/bin/env python3
"""Generate LaTeX metric tables and prose macros from data/metrics.json.

Outputs (manuscript/tables/):
  resources-a021.tex  A021 resource and work metrics, grouped vs independent
  resources-r2.tex    R2 resource and work metrics, both orchestration definitions
  quality-counts.tex  test and defect counts per evaluation (counts only)
  macros.tex          \\newcommand for every number used in prose

Every number comes from metrics.json; nothing is typed by hand. Plain
``tabular`` with \\hline (compatible with IEEEtran; no booktabs needed).
Markers: ``$\\geq$`` lower bound; ``n/a`` unknown; ``--`` not applicable;
``$^{\\ast}$`` ratio/reduction computed from partial or lower-bound operands.
No p-values, confidence intervals or cross-study means are produced.

Usage: python3 scripts/build_tables.py [--check]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from types import MappingProxyType
from typing import Any, Callable, Mapping, NamedTuple, Optional, Sequence

PKG = Path(__file__).resolve().parent.parent
DATA = PKG / "data" / "metrics.json"
OUT = PKG / "manuscript" / "tables"

HEADER = "% Generated by scripts/build_tables.py from data/metrics.json. Do not edit.\n"

# --------------------------------------------------------------------------
# Formatting (pure)
# --------------------------------------------------------------------------

Fmt = Callable[[Any], str]

FMT: Mapping[str, Fmt] = MappingProxyType({
    "int": lambda v: f"{int(v):,}",
    "usd": lambda v: f"{v:.2f}",
    "usd7": lambda v: f"{v:.7f}",
    "mtok": lambda v: f"{v / 1e6:.2f}",
    "ktok": lambda v: f"{v / 1e3:.1f}",
    "min": lambda v: f"{v / 60:.1f}",
    "hmin": lambda v: f"{int(v) // 3600}:{round((int(v) % 3600) / 60):02d}",
    "hms": lambda v: (lambda s: f"{s // 3600}h{(s % 3600) // 60:02d}m{s % 60:02d}s")(int(round(v))),
    "ratio": lambda v: f"{v:.2f}",
    "ratio4": lambda v: f"{v:.4f}",
    "pct1": lambda v: f"{v * 100:.1f}",
    "pct2": lambda v: f"{v * 100:.2f}",
})


def cell(r: Optional[Mapping[str, Any]], fmt: str) -> str:
    if r is None:
        return "--"
    if r["value"] is None:
        return "--" if r["completeness"] == "not_applicable" else "n/a"
    text = FMT[fmt](r["value"])
    return ("$\\geq$" + text) if r["completeness"] == "lower_bound" else text


def dcell(d: Optional[Mapping[str, Any]], field: str, fmt: str) -> str:
    if d is None or d[field] is None:
        return "n/a"
    text = FMT[fmt](d[field])
    return text + ("$^{\\ast}$" if d["completeness"] != "complete" else "")


def tex_escape(s: str) -> str:
    return s.replace("%", "\\%").replace("&", "\\&").replace("_", "\\_").replace("#", "\\#")


# --------------------------------------------------------------------------
# Table specification
# --------------------------------------------------------------------------

class Line(NamedTuple):
    label: str
    metric: str
    unit_g: str        # aggregate unit for grouped
    unit_i: str        # aggregate unit for independent
    fmt: str
    derived_unit: Optional[str]   # unit key in the derived section, or None for no ratio
    session_i: Optional[str] = None  # use one session instead of the aggregate (independent)
    session_g: Optional[str] = None


W, A, WO = "agg:workers", "agg:arm", "agg:workers+orchestration"

A021_LINES: tuple[Line, ...] = (
    Line("Implementation sessions", "sessions_implementation", A, A, "int", None),
    Line("Failed attempt sessions", "sessions_failed_attempt", A, A, "int", None),
    Line("Cost, platform (USD)", "cost_usd_platform", W, W, "usd", W),
    Line("Output tokens, platform (k)", "output_tokens_platform", W, W, "ktok", W),
    Line("Cache-read tokens, platform (M)", "cache_read_tokens_platform", W, W, "mtok", W),
    Line("Cache-write tokens, platform (k)", "cache_write_tokens_platform", W, W, "ktok", W),
    Line("Uncached input tokens, platform", "input_tokens_platform", W, W, "int", W),
    Line("Active session time, sum (min)", "active_session_sum_s", W, W, "min", W),
    Line("Wall-clock span, first start to last end (h:mm)", "wall_clock_span_s", W, W, "hmin", W),
    Line("Blocked on a permission prompt (min)", "blocked_time_s", W, W, "min", None),
    Line("Largest end-of-session context (k tokens)", "context_tokens_at_end_platform", W, W, "ktok", None),
    Line("Model requests, script", "model_requests_transcript", W, W, "int", W),
    Line("File reads, script", "file_reads_transcript", W, W, "int", W),
    Line("Searches, script", "searches_transcript", W, W, "int", W),
    Line("Build commands, script", "builds_transcript", W, W, "int", W),
    Line("Test-run commands, script", "test_runs_transcript", W, W, "int", W),
    Line("AGENTS.md reads, script", "agents_md_reads_transcript", W, W, "int", W),
    Line("Governance/planning document reads, script", "governance_reads_transcript", W, W, "int", W),
    Line("Time to first code change, summed (min)", "time_to_first_code_s", W, W, "min", W),
    Line("Compactions", "compactions_transcript", W, W, "int", None),
    Line("Merges with conflicts", "merges_with_conflicts", A, A, "int", None),
    Line("Commits after baseline", "commits", A, A, "int", None),
)

R2_LINES: tuple[Line, ...] = (
    Line("Implementation sessions", "sessions_implementation", A, A, "int", None),
    Line("Arm orchestration sessions", "sessions_orchestration", A, A, "int", None),
    Line("Cost, platform, workers (USD)", "cost_usd_platform", W, W, "usd", W),
    Line("Cost, platform, incl.\\ orchestrator (USD)", "cost_usd_platform", WO, WO, "usd", WO),
    Line("Output tokens, platform, workers (k)", "output_tokens_platform", W, W, "ktok", W),
    Line("Output tokens, platform, incl.\\ orchestrator (k)", "output_tokens_platform", WO, WO, "ktok", WO),
    Line("Cache-read tokens, platform, workers (M)", "cache_read_tokens_platform", W, W, "mtok", W),
    Line("Cache-read tokens, platform, incl.\\ orchestrator (M)", "cache_read_tokens_platform", WO, WO, "mtok", WO),
    Line("Cache-write tokens, platform, workers (k)", "cache_write_tokens_platform", W, W, "ktok", W),
    Line("Active session time, workers, sum (min)", "active_session_sum_s", W, W, "min", W),
    Line("Wall-clock span, workers (h:mm)", "wall_clock_span_s", W, W, "hmin", W),
    Line("Wall-clock span from common start, incl.\\ orchestrator (h:mm)", "wall_clock_span_from_common_start_s", WO, WO, "hmin", WO),
    Line("Model requests, script", "model_requests_transcript", W, W, "int", W),
    Line("File reads, script", "file_reads_transcript", W, W, "int", W),
    Line("Searches, script", "searches_transcript", W, W, "int", W),
    Line("Build commands, script", "builds_transcript", W, W, "int", W),
    Line("Test-run commands, script", "test_runs_transcript", W, W, "int", W),
    Line("AGENTS.md reads, script", "agents_md_reads_transcript", W, W, "int", W),
    Line("Governance/planning document reads, script", "governance_reads_transcript", W, W, "int", W),
    Line("Time to first code change, summed (min)", "time_to_first_code_s", W, W, "min", W),
    Line("Compactions", "compactions_transcript", W, W, "int", None),
    Line("Merges with conflicts", "merges_with_conflicts", A, A, "int", None),
    Line("Commits after baseline", "commits", A, A, "int", None),
)

QUALITY_LINES: tuple[tuple[str, str, str, str], ...] = (
    # label, study, metric, fmt
    ("A021: final F\\# tests passed", "A021", "fsharp_tests_passed_final", "int"),
    ("A021: work-group tests added (evaluation 1)", "A021", "tests_added", "int"),
    ("A021: acceptance rows partially met (evaluation 1)", "A021", "acceptance_rows_partially_met_eval1", "int"),
    ("A021: findings labelled defect (kit evaluation)", "A021", "findings_defect_kit", "int"),
    ("A021: findings labelled inconsistency (kit evaluation)", "A021", "findings_inconsistency_kit", "int"),
    ("R2: final F\\# tests passed", "R2", "fsharp_tests_passed_final", "int"),
    ("R2: net F\\# tests added vs.\\ baseline", "R2", "fsharp_tests_net_added", "int"),
    ("R2: confirmed acceptance defects", "R2", "confirmed_acceptance_defects_r2", "int"),
    ("R2: design risks", "R2", "design_risks_r2", "int"),
)


class Index(NamedTuple):
    rows: Mapping[tuple[str, str, str, str], Mapping[str, Any]]
    derived: Mapping[tuple[str, str, str], Mapping[str, Any]]


def index(doc: Mapping[str, Any]) -> Index:
    return Index(
        MappingProxyType({(r["study"], r["arm"], r["unit"], r["metric"]): r for r in doc["rows"]}),
        MappingProxyType({(d["study"], d["unit"], d["metric"]): d for d in doc["derived"]}))


def line_tex(ix: Index, study: str, ln: Line) -> str:
    g = ix.rows.get((study, "grouped", ln.session_g or ln.unit_g, ln.metric))
    i = ix.rows.get((study, "independent", ln.session_i or ln.unit_i, ln.metric))
    d = ix.derived.get((study, ln.derived_unit, ln.metric)) if ln.derived_unit else None
    ratio = dcell(d, "ratio_independent_over_grouped", "ratio") if ln.derived_unit else "--"
    red = dcell(d, "reduction_grouped_vs_independent", "pct1") if ln.derived_unit else "--"
    return f"{ln.label} & {cell(g, ln.fmt)} & {cell(i, ln.fmt)} & {ratio} & {red} \\\\"


def resource_table(ix: Index, study: str, lines: Sequence[Line], caption: str, label: str, notes: str) -> str:
    body = "\n".join(line_tex(ix, study, ln) for ln in lines)
    return (HEADER +
            "\\begin{table}[t]\n\\centering\n\\scriptsize\n"
            f"\\caption{{{caption}}}\n\\label{{{label}}}\n"
            "\\begin{tabular}{@{}p{0.44\\columnwidth}rrrr@{}}\n\\hline\n"
            "Measure & Grouped & Indep. & I/G & Red.\\ (\\%) \\\\\n\\hline\n"
            f"{body}\n\\hline\n\\end{{tabular}}\n\n"
            f"\\vspace{{2pt}}\\parbox{{\\columnwidth}}{{\\scriptsize {notes}}}\n"
            "\\end{table}\n")


A021_NOTES = ("Grouped: one session. Independent: five item sessions plus two failed item-04 attempts; the shared "
              "orchestrator and the evaluator are excluded. Platform figures are whole-session get\\_session usage. "
              "``Script'' figures come from each session's own session\\_metrics.py run, taken before its final "
              "steps; the independent arm has none for the two failed attempts. I/G is the independent/grouped "
              "ratio; Red.\\ is (independent$-$grouped)/independent. $\\geq$: lower bound. $^{\\ast}$: computed from "
              "partial or lower-bound operands, so it is not a bound on the true value. Active time ends a "
              "blocked session at the block; the wall-clock span includes orchestration gaps and the block. "
              "End-of-session context approximates the peak (no compactions).")

R2_NOTES = ("Grouped: one session. Independent: five worker sessions (``workers'') and the arm's own orchestrator "
            "session, which created the workers and waited for each one; ``incl.\\ orchestrator'' adds it. Only "
            "the workers rows are defined as in A021. The common-start span runs from the grouped session's "
            "creation to the orchestrator's last update; it is the R2 record's ``elapsed''. Script figures were "
            "captured before each session's final steps; one worker's build count is not recoverable. "
            "Markers as in Table~\\ref{tab:resources-a021}.")


def quality_table(ix: Index) -> str:
    def q(study: str, arm: str, metric: str, fmt: str) -> str:
        return cell(ix.rows.get((study, arm, "agg:arm", metric)), fmt)
    body = "\n".join(f"{label} & {q(st, 'grouped', m, f)} & {q(st, 'independent', m, f)} \\\\"
                     for label, st, m, f in QUALITY_LINES)
    return (HEADER +
            "\\begin{table}[t]\n\\centering\n\\scriptsize\n"
            "\\caption{Test and defect counts reported by each evaluation (counts only; see text for what each "
            "evaluation classified)}\n\\label{tab:quality-counts}\n"
            "\\begin{tabular}{@{}p{0.6\\columnwidth}rr@{}}\n\\hline\n"
            "Measure & Grouped & Indep. \\\\\n\\hline\n"
            f"{body}\n\\hline\n\\end{{tabular}}\n\\end{{table}}\n")


# --------------------------------------------------------------------------
# Macros
# --------------------------------------------------------------------------

class Macro(NamedTuple):
    name: str
    kind: str        # row | derived | excluded
    key: tuple
    fmt: str
    comment: str


def rowm(name: str, study: str, arm: str, unit: str, metric: str, fmt: str, comment: str) -> Macro:
    return Macro(name, "row", (study, arm, unit, metric), fmt, comment)


def derm(name: str, study: str, unit: str, metric: str, field: str, fmt: str, comment: str) -> Macro:
    return Macro(name, "derived", (study, unit, metric, field), fmt, comment)


def exclm(name: str, study: str, unit: str, metric: str, session_metric: str,
          excluded: tuple[str, ...], fmt: str, comment: str) -> Macro:
    """Sensitivity: grouped reduction after removing named independent sessions from the aggregate."""
    return Macro(name, "excluded", (study, unit, metric, session_metric, excluded), fmt, comment)


G, I = "grouped", "independent"
FAILED_A021 = ("control-04-attempt-1", "control-04-attempt-2")


def arm_pair(prefix: str, study: str, unit: str, metric: str, fmt: str, what: str) -> tuple[Macro, ...]:
    return (rowm(f"{prefix}Grouped", study, G, unit, metric, fmt, f"{what}, grouped"),
            rowm(f"{prefix}Indep", study, I, unit, metric, fmt, f"{what}, independent"))


def comparison(prefix: str, study: str, unit: str, metric: str, what: str, rfmt: str = "ratio", pfmt: str = "pct1") -> tuple[Macro, ...]:
    return (derm(f"{prefix}Ratio", study, unit, metric, "ratio_independent_over_grouped", rfmt, f"{what}, independent/grouped"),
            derm(f"{prefix}Reduction", study, unit, metric, "reduction_grouped_vs_independent", pfmt, f"{what}, grouped reduction in percent"))


MACROS: tuple[Macro, ...] = (
    # A021 resources
    *arm_pair("Acost", "A021", W, "cost_usd_platform", "usd", "A021 platform cost USD"),
    *comparison("Acost", "A021", W, "cost_usd_platform", "A021 platform cost"),
    *arm_pair("Aoutput", "A021", W, "output_tokens_platform", "int", "A021 platform output tokens"),
    *comparison("Aoutput", "A021", W, "output_tokens_platform", "A021 platform output tokens"),
    *arm_pair("AcacheRead", "A021", W, "cache_read_tokens_platform", "mtok", "A021 platform cache-read tokens, millions"),
    *comparison("AcacheRead", "A021", W, "cache_read_tokens_platform", "A021 platform cache-read tokens"),
    *arm_pair("AactiveMin", "A021", W, "active_session_sum_s", "min", "A021 active session time, minutes"),
    *comparison("Aactive", "A021", W, "active_session_sum_s", "A021 active session time"),
    *arm_pair("AspanMin", "A021", W, "wall_clock_span_s", "min", "A021 wall-clock span, minutes"),
    rowm("AspanHmIndep", "A021", I, W, "wall_clock_span_s", "hmin", "A021 wall-clock span, independent, h:mm"),
    *comparison("Aspan", "A021", W, "wall_clock_span_s", "A021 wall-clock span"),
    rowm("AblockedMinIndep", "A021", I, W, "blocked_time_s", "min", "A021 permission-block time, minutes"),
    *arm_pair("Asessions", "A021", A, "sessions_implementation", "int", "A021 implementation sessions"),
    rowm("AfailedAttemptsIndep", "A021", I, A, "sessions_failed_attempt", "int", "A021 failed attempt sessions"),
    *arm_pair("AmodelRequests", "A021", W, "model_requests_transcript", "int", "A021 model requests (script; independent is a lower bound)"),
    *arm_pair("AfileReads", "A021", W, "file_reads_transcript", "int", "A021 file reads (script; independent lower bound)"),
    *arm_pair("Asearches", "A021", W, "searches_transcript", "int", "A021 searches (script; independent lower bound)"),
    *arm_pair("Abuilds", "A021", W, "builds_transcript", "int", "A021 build commands (script)"),
    *arm_pair("AtestRuns", "A021", W, "test_runs_transcript", "int", "A021 test-run commands (script)"),
    *arm_pair("AagentsReads", "A021", W, "agents_md_reads_transcript", "int", "A021 AGENTS.md reads"),
    *arm_pair("AgovReads", "A021", W, "governance_reads_transcript", "int", "A021 governance/planning reads"),
    *arm_pair("AfirstCodeMin", "A021", W, "time_to_first_code_s", "min", "A021 summed time to first code change, minutes"),
    *arm_pair("AcontextK", "A021", W, "context_tokens_at_end_platform", "ktok", "A021 largest end-of-session context, k tokens"),
    *arm_pair("Atests", "A021", A, "fsharp_tests_passed_final", "int", "A021 final F# tests passed"),
    *arm_pair("AtestsAdded", "A021", A, "tests_added", "int", "A021 work-group tests added (evaluation 1)"),
    *arm_pair("AkitDefects", "A021", A, "findings_defect_kit", "int", "A021 kit-evaluation defect findings"),
    *arm_pair("AmergeConflicts", "A021", A, "merges_with_conflicts", "int", "A021 merges with conflicts"),
    # R2 resources, A021-comparable definition (workers)
    *arm_pair("RtwoCost", "R2", W, "cost_usd_platform", "usd", "R2 platform cost USD, workers"),
    *comparison("RtwoCost", "R2", W, "cost_usd_platform", "R2 platform cost, workers"),
    *arm_pair("RtwoOutput", "R2", W, "output_tokens_platform", "int", "R2 platform output tokens, workers"),
    *comparison("RtwoOutput", "R2", W, "output_tokens_platform", "R2 platform output tokens, workers"),
    *arm_pair("RtwoCacheRead", "R2", W, "cache_read_tokens_platform", "mtok", "R2 platform cache-read tokens, millions, workers"),
    *comparison("RtwoCacheRead", "R2", W, "cache_read_tokens_platform", "R2 platform cache-read tokens, workers"),
    *arm_pair("RtwoActiveMin", "R2", W, "active_session_sum_s", "min", "R2 active session time, workers, minutes"),
    *comparison("RtwoActive", "R2", W, "active_session_sum_s", "R2 active session time, workers"),
    *arm_pair("RtwoSpanMin", "R2", W, "wall_clock_span_s", "min", "R2 wall-clock span, workers, minutes"),
    *comparison("RtwoSpan", "R2", W, "wall_clock_span_s", "R2 wall-clock span, workers"),
    # R2 as reported (incl. orchestrator; common-start span)
    rowm("RtwoCostInclOrchIndep", "R2", I, WO, "cost_usd_platform", "usd", "R2 platform cost USD, independent incl. orchestrator"),
    rowm("RtwoOrchCostIndep", "R2", I, "control-orchestrator", "cost_usd_platform", "usd", "R2 independent-arm orchestrator cost USD"),
    *comparison("RtwoCostInclOrch", "R2", WO, "cost_usd_platform", "R2 platform cost incl. orchestrator", "ratio4", "pct2"),
    *comparison("RtwoOutputInclOrch", "R2", WO, "output_tokens_platform", "R2 output tokens incl. orchestrator", "ratio4", "pct2"),
    *comparison("RtwoCacheReadInclOrch", "R2", WO, "cache_read_tokens_platform", "R2 cache-read incl. orchestrator", "ratio4", "pct2"),
    rowm("RtwoElapsedGrouped", "R2", G, WO, "wall_clock_span_from_common_start_s", "hms", "R2 elapsed as reported, grouped"),
    rowm("RtwoElapsedIndep", "R2", I, WO, "wall_clock_span_from_common_start_s", "hms", "R2 elapsed as reported, independent"),
    *comparison("RtwoElapsed", "R2", WO, "wall_clock_span_from_common_start_s", "R2 elapsed as reported (wall-clock incl. orchestration)", "ratio4", "pct2"),
    *arm_pair("RtwoSessions", "R2", A, "sessions_implementation", "int", "R2 implementation sessions"),
    *arm_pair("RtwoModelRequests", "R2", W, "model_requests_transcript", "int", "R2 model requests (script)"),
    *arm_pair("RtwoFileReads", "R2", W, "file_reads_transcript", "int", "R2 file reads (script)"),
    *arm_pair("RtwoSearches", "R2", W, "searches_transcript", "int", "R2 searches (script)"),
    *arm_pair("RtwoAgentsReads", "R2", W, "agents_md_reads_transcript", "int", "R2 AGENTS.md reads"),
    *arm_pair("RtwoGovReads", "R2", W, "governance_reads_transcript", "int", "R2 governance/planning reads"),
    *arm_pair("RtwoFirstCodeMin", "R2", W, "time_to_first_code_s", "min", "R2 summed time to first code change, minutes"),
    *arm_pair("RtwoTests", "R2", A, "fsharp_tests_passed_final", "int", "R2 final F# tests passed"),
    *arm_pair("RtwoTestsAdded", "R2", A, "fsharp_tests_net_added", "int", "R2 net F# tests added vs baseline"),
    *arm_pair("RtwoDefects", "R2", A, "confirmed_acceptance_defects_r2", "int", "R2 confirmed acceptance defects"),
    *arm_pair("RtwoMergeConflicts", "R2", A, "merges_with_conflicts", "int", "R2 merges with conflicts"),
    rowm("BaselineTests", "A021", G, A, "fsharp_tests_preexisting", "int", "F# tests at the shared baseline"),
    # Sensitivity S1: A021 without the two failed item-04 attempts
    exclm("AcostReductionExclFailed", "A021", W, "cost_usd_platform", "cost_usd_platform", FAILED_A021, "pct1",
          "A021 platform cost, grouped reduction in percent, excluding failed attempts"),
    exclm("AactiveReductionExclFailed", "A021", W, "active_session_sum_s", "session_duration_s", FAILED_A021, "pct1",
          "A021 active session time, grouped reduction in percent, excluding failed attempts"),
)


def excluded_reduction(ix: Index, study: str, unit: str, metric: str, session_metric: str,
                       excluded: tuple[str, ...]) -> float:
    def value(arm: str, u: str, met: str) -> float:
        r = ix.rows.get((study, arm, u, met))
        if r is None or r["value"] is None or r["completeness"] != "complete":
            raise KeyError(f"excluded-sessions macro: no complete row {(study, arm, u, met)}")
        return r["value"]
    grouped = value(G, unit, metric)
    independent = value(I, unit, metric) - sum(value(I, u, session_metric) for u in excluded)
    return (independent - grouped) / independent


def macro_value(ix: Index, m: Macro) -> str:
    if m.kind == "excluded":
        return FMT[m.fmt](excluded_reduction(ix, *m.key))
    if m.kind == "row":
        r = ix.rows.get(m.key)
        if r is None:
            raise KeyError(f"macro {m.name}: no row {m.key}")
        return cell(r, m.fmt).replace("$\\geq$", "\\ensuremath{\\geq}")
    d = ix.derived.get(m.key[:3])
    if d is None:
        raise KeyError(f"macro {m.name}: no derived {m.key}")
    return "n/a" if d[m.key[3]] is None else FMT[m.fmt](d[m.key[3]])


def macros_tex(ix: Index) -> str:
    names = [m.name for m in MACROS]
    dupes = sorted({n for n in names if names.count(n) > 1})
    bad = sorted(n for n in names if not n.isalpha())
    if dupes or bad:
        raise ValueError(f"macro names: duplicates {dupes}, non-letters {bad}")
    lines = (f"\\newcommand{{\\{m.name}}}{{{macro_value(ix, m)}}} % {tex_escape(m.comment)}" for m in MACROS)
    return (HEADER + "% Numbers only (no units or % signs). Lower bounds carry \\ensuremath{\\geq}.\n"
            "% Reductions are percentages; ratios are independent/grouped.\n" + "\n".join(lines) + "\n")


def render(doc: Mapping[str, Any]) -> Mapping[str, str]:
    ix = index(doc)
    return MappingProxyType({
        "resources-a021.tex": resource_table(ix, "A021", A021_LINES,
                                             "A021 resources and repeated work, grouped versus independent execution",
                                             "tab:resources-a021", A021_NOTES),
        "resources-r2.tex": resource_table(ix, "R2", R2_LINES,
                                           "R2 resources and repeated work, grouped versus independent execution",
                                           "tab:resources-r2", R2_NOTES),
        "quality-counts.tex": quality_table(ix),
        "macros.tex": macros_tex(ix),
    })


def main(argv: Sequence[str]) -> int:
    files = render(json.loads(DATA.read_text(encoding="utf-8")))
    if "--check" in argv:
        stale = tuple(n for n, t in sorted(files.items())
                      if not (OUT / n).exists() or (OUT / n).read_text(encoding="utf-8") != t)
        tuple(print(f"STALE manuscript/tables/{n}") for n in stale)
        print("tables up to date" if not stale else f"{len(stale)} table file(s) differ")
        return 1 if stale else 0
    OUT.mkdir(parents=True, exist_ok=True)
    tuple((OUT / n).write_text(t, encoding="utf-8") for n, t in sorted(files.items()))
    print("\n".join(f"manuscript/tables/{n}" for n in sorted(files)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
