#!/usr/bin/env python3
"""Generate the architecture matrix, the replication matrix and architecture count macros.

Inputs (read only):
  data/architecture-findings.json  8-dimension rubric applied to both arms of both studies
  data/metrics.json                derived independent/grouped ratios and arm-level counts

Outputs (manuscript/tables/):
  architecture-matrix.tex   D1-D8 x {A021, R2}: grouped/independent category, direction, behavioral flag
  replication-matrix.tex    outcome x {A021, R2} with a replication status
  architecture-macros.tex   \\newcommand counts used in prose (dimension tallies, findings, citations)

Replication status rules (applied mechanically, never typed by hand):
  reproduced      the same non-mixed direction was observed in both studies
  mixed           at least one study shows a mixed direction on the outcome
  not reproduced  A021 showed a direction that R2 did not show
  not tested      the outcome was not measured in at least one study (or in neither)

Deterministic output; stdlib only. No p-values, intervals or cross-study means.

Usage: python3 scripts/build_architecture_table.py [--check]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from types import MappingProxyType
from typing import Any, Mapping, NamedTuple, Optional, Sequence

PKG = Path(__file__).resolve().parent.parent
ARCH = PKG / "data" / "architecture-findings.json"
METRICS = PKG / "data" / "metrics.json"
OUT = PKG / "manuscript" / "tables"

HEADER = ("% Generated by scripts/build_architecture_table.py from data/architecture-findings.json "
          "and data/metrics.json. Do not edit.\n")

STUDIES = ("A021", "R2")
W = "agg:workers"
ARM = "agg:arm"

CATEGORY_ABBR: Mapping[str, str] = MappingProxyType({
    "unified": "U", "duplicated-compatible": "DC", "divergent": "Dv",
    "missing": "Mi", "not-assessable": "NA"})

DIRECTION_ABBR: Mapping[str, str] = MappingProxyType({
    "grouped_more_unified": "G", "independent_more_unified": "I",
    "equivalent": "eq", "mixed": "mixed", "not_assessable": "NA"})

SHORT_NAMES: Mapping[str, str] = MappingProxyType({
    "D1": "Persistence/store model",
    "D2": "Member admission (create vs.\\ add)",
    "D3": "Member classification (show vs.\\ checkpoint)",
    "D4": "Checkpoint ownership validation",
    "D5": "Error/JSON/exit contract",
    "D6": "Mutation/concurrency model",
    "D7": "Reuse of baseline rules",
    "D8": "Incompatible duplicates in feature"})


# --------------------------------------------------------------------------
# Pure helpers
# --------------------------------------------------------------------------

def comparisons(arch: Mapping[str, Any]) -> Mapping[tuple[str, str], Mapping[str, Any]]:
    return MappingProxyType({(c["study"], c["dimension"]): c for c in arch["comparisons"]})


def stale_sensitive(arch: Mapping[str, Any]) -> frozenset[tuple[str, str, str]]:
    """(study, dimension, arm) whose finding depends on a stale-start item."""
    arm_of = {i["id"]: i["arm"] for i in arch["implementations"]}
    return frozenset((f["study"], f["dimension"], arm_of[f["implementation"]])
                     for f in arch["findings"] if f["stale_start_sensitive"] is True)


def dimensions(arch: Mapping[str, Any]) -> tuple[str, ...]:
    return tuple(d["id"] for d in arch["rubric"]["dimensions"])


def tally(arch: Mapping[str, Any], study: str) -> Mapping[str, int]:
    cs = tuple(c for c in arch["comparisons"] if c["study"] == study)
    return MappingProxyType({
        "groupedMore": sum(c["direction"] == "grouped_more_unified" for c in cs),
        "groupedBeh": sum(c["direction"] == "grouped_more_unified" and c["behavioral_difference"] for c in cs),
        "indepMore": sum(c["direction"] == "independent_more_unified" for c in cs),
        "mixed": sum(c["direction"] == "mixed" for c in cs),
        "equivalent": sum(c["direction"] == "equivalent" for c in cs),
    })


def word(n: int) -> str:
    return ("zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten")[n] if 0 <= n <= 10 else str(n)


# --------------------------------------------------------------------------
# Architecture matrix
# --------------------------------------------------------------------------

def arch_cells(cmp_: Mapping[str, Any], stale: frozenset, study: str, dim: str) -> str:
    dag = "$^{\\dagger}$"
    g = CATEGORY_ABBR[cmp_["grouped_category"]] + (dag if (study, dim, "grouped") in stale else "")
    i = CATEGORY_ABBR[cmp_["independent_category"]] + (dag if (study, dim, "independent") in stale else "")
    d = DIRECTION_ABBR[cmp_["direction"]] + ("$^{b}$" if cmp_["behavioral_difference"] else "")
    return f"{g}/{i} & {d}"


def architecture_matrix(arch: Mapping[str, Any]) -> str:
    cs, stale = comparisons(arch), stale_sensitive(arch)
    rows = "\n".join(
        f"{dim} {SHORT_NAMES[dim]} & " + " & ".join(arch_cells(cs[(s, dim)], stale, s, dim) for s in STUDIES) + " \\\\"
        for dim in dimensions(arch))
    t = {s: tally(arch, s) for s in STUDIES}
    summary = "\n".join(
        f"\\multicolumn{{5}}{{@{{}}l}}{{{s} tally: G more unified {t[s]['groupedMore']} "
        f"({t[s]['groupedBeh']} behavioral), I more unified {t[s]['indepMore']}, mixed {t[s]['mixed']}, "
        f"equivalent {t[s]['equivalent']}}} \\\\" for s in STUDIES)
    notes = ("Cells: grouped/independent category. U unified; DC duplicated-compatible; Dv divergent; Mi missing. "
             "Direction: G grouped more unified; I independent more unified; mixed; eq equivalent. "
             "$^{b}$: the arms differ in observable behavior (otherwise the difference is organizational only). "
             "$^{\\dagger}$: the finding comes from an item whose session started from a stale checkout. "
             "Rubric applied after unblinding by one auditor; no inter-rater reliability.")
    return (HEADER +
            "\\begin{table}[t]\n\\centering\n\\scriptsize\n\\setlength{\\tabcolsep}{3pt}\n"
            "\\caption{Architecture rubric: category per arm and direction per study}\n"
            "\\label{tab:architecture}\n"
            "\\begin{tabular}{@{}p{0.40\\columnwidth}cccc@{}}\n\\hline\n"
            " & \\multicolumn{2}{c}{A021} & \\multicolumn{2}{c}{R2} \\\\\n"
            "Dimension & G/I & Dir. & G/I & Dir. \\\\\n\\hline\n"
            f"{rows}\n\\hline\n{summary}\n\\hline\n\\end{{tabular}}\n\n"
            f"\\vspace{{2pt}}\\parbox{{\\columnwidth}}{{\\scriptsize {notes}}}\n"
            "\\end{table}\n")


# --------------------------------------------------------------------------
# Replication matrix
# --------------------------------------------------------------------------

class Rep(NamedTuple):
    family: str
    outcome: str
    a021: str
    r2: str
    status: str


def derived_index(metrics: Mapping[str, Any]) -> Mapping[tuple[str, str, str], Mapping[str, Any]]:
    return MappingProxyType({(d["study"], d["unit"], d["metric"]): d for d in metrics["derived"]})


def row_index(metrics: Mapping[str, Any]) -> Mapping[tuple[str, str, str, str], Mapping[str, Any]]:
    return MappingProxyType({(r["study"], r["arm"], r["unit"], r["metric"]): r for r in metrics["rows"]})


def sign_word(reduction: Optional[float], fewer: str) -> Optional[str]:
    if reduction is None:
        return None
    return f"G {fewer}" if reduction > 0 else ("I " + fewer if reduction < 0 else "equal")


def status_from(a: Optional[str], b: Optional[str]) -> str:
    if a is None or b is None:
        return "not tested"
    if "mixed" in (a, b):
        return "mixed"
    return "reproduced" if a == b else "not reproduced"


def resource_rep(dix: Mapping, label: str, metric: str, fewer: str, family: str) -> Rep:
    def cell(study: str) -> tuple[Optional[str], str]:
        d = dix.get((study, W, metric))
        if d is None or d["ratio_independent_over_grouped"] is None:
            return None, "n/a"
        mark = "" if d["completeness"] == "complete" else "$^{\\ast}$"
        direction = sign_word(d["reduction_grouped_vs_independent"], fewer)
        return direction, f"{direction}, {d['ratio_independent_over_grouped']:.2f}{mark}"
    (da, ca), (db, cb) = cell("A021"), cell("R2")
    return Rep(family, label, ca, cb, status_from(da, db))


def arch_rep(cs: Mapping, dim: str) -> Rep:
    def direction(study: str) -> Optional[str]:
        c = cs.get((study, dim))
        return None if c is None else DIRECTION_ABBR[c["direction"]]
    def cell(study: str) -> str:
        c = cs.get((study, dim))
        if c is None:
            return "n/a"
        d = DIRECTION_ABBR[c["direction"]]
        text = {"G": "G", "I": "I", "eq": "equivalent", "mixed": "mixed"}.get(d, d)
        return text + (", beh." if c["behavioral_difference"] else ", org." if d in ("G", "I") else "")
    da, db = direction("A021"), direction("R2")
    status = ("not reproduced" if da in ("G", "I") and db not in (da, None) and db != "mixed"
              else status_from(da, db))
    return Rep("Architecture", f"{dim} {SHORT_NAMES[dim]}", cell("A021"), cell("R2"), status)


def lc_rep(arch: Mapping[str, Any], label: str, ids: Sequence[str], arm: str) -> Rep:
    impls = frozenset(i for lc in arch["local_correctness"] if lc["id"] in ids for i in lc["implementations"])
    seen = {s: f"{s}-{arm}" in impls for s in STUDIES}
    cell = {s: ("observed" if seen[s] else "not observed") for s in STUDIES}
    status = "reproduced" if all(seen.values()) else ("not reproduced" if seen["A021"] else "not tested")
    return Rep("Local correctness", label, cell["A021"], cell["R2"], status)


def count_rep(rix: Mapping, label: str, metric_by_study: Mapping[str, str]) -> Rep:
    def pair(study: str) -> Optional[tuple[int, int]]:
        g = rix.get((study, "grouped", ARM, metric_by_study[study]))
        i = rix.get((study, "independent", ARM, metric_by_study[study]))
        if g is None or i is None or g["value"] is None or i["value"] is None:
            return None
        return int(g["value"]), int(i["value"])
    def direction(p: Optional[tuple[int, int]]) -> Optional[str]:
        return None if p is None else ("I more" if p[1] > p[0] else "G more" if p[0] > p[1] else "tie")
    def cell(p: Optional[tuple[int, int]]) -> str:
        return "no comparable tally" if p is None else f"{direction(p)} ({p[0]} vs.\\ {p[1]})"
    pa, pb = pair("A021"), pair("R2")
    return Rep("Local correctness", label, cell(pa), cell(pb), status_from(direction(pa), direction(pb)))


NOT_TESTED: tuple[tuple[str, str], ...] = (
    ("Generalization", "Other repository or feature family"),
    ("Generalization", "Low-affinity cohort (planned study blocked)"),
    ("Generalization", "Other implementing models or runtimes"),
    ("Generalization", "Larger cohorts / context pressure"),
    ("Mechanism", "Retained context vs.\\ mandated analysis separated"),
)


def replication_rows(arch: Mapping[str, Any], metrics: Mapping[str, Any]) -> tuple[Rep, ...]:
    dix, rix, cs = derived_index(metrics), row_index(metrics), comparisons(arch)
    resources = (
        resource_rep(dix, "Platform cost (workers)", "cost_usd_platform", "lower", "Resources"),
        resource_rep(dix, "Output tokens (workers)", "output_tokens_platform", "lower", "Resources"),
        resource_rep(dix, "Cache-read tokens (workers)", "cache_read_tokens_platform", "lower", "Resources"),
        resource_rep(dix, "Summed active session time", "active_session_sum_s", "lower", "Resources"),
        resource_rep(dix, "Model requests (script)", "model_requests_transcript", "fewer", "Repeated context"),
        resource_rep(dix, "File reads (script)", "file_reads_transcript", "fewer", "Repeated context"),
        resource_rep(dix, "Searches (script)", "searches_transcript", "fewer", "Repeated context"),
        resource_rep(dix, "Governance/planning reads (script)", "governance_reads_transcript", "fewer", "Repeated context"),
    )
    architecture = tuple(arch_rep(cs, dim) for dim in dimensions(arch))
    local = (
        count_rep(rix, "Tests added", {"A021": "tests_added", "R2": "fsharp_tests_net_added"}),
        count_rep(rix, "Confirmed acceptance defects",
                  {"A021": "confirmed_acceptance_defects_r2", "R2": "confirmed_acceptance_defects_r2"}),
        lc_rep(arch, "Grouped add admits external item (P2)", ("LC-01",), "grouped"),
        lc_rep(arch, "Grouped checkpoint does not reject blank decision", ("LC-05", "LC-06"), "grouped"),
        lc_rep(arch, "Independent concurrent creates lose updates", ("LC-04",), "independent"),
    )
    untested = tuple(Rep(f, o, "--", "--", "not tested") for f, o in NOT_TESTED)
    return resources + architecture + local + untested


def replication_matrix(arch: Mapping[str, Any], metrics: Mapping[str, Any]) -> str:
    reps = replication_rows(arch, metrics)
    families = tuple(dict.fromkeys(r.family for r in reps))
    body = "\n".join(
        f"\\multicolumn{{4}}{{@{{}}l}}{{\\textit{{{fam}}}}} \\\\\n" +
        "\n".join(f"{r.outcome} & {r.a021} & {r.r2} & {r.status} \\\\" for r in reps if r.family == fam)
        for fam in families)
    notes = ("G grouped; I independent. Resource and repeated-context cells give the direction and the "
             "independent/grouped ratio; resource rows use worker-only platform figures (A021 definition). Script counts are lower bounds; $^{\\ast}$ marks a ratio of "
             "lower-bound operands. Architecture rows: the arm that is more unified (Table~\\ref{tab:architecture}); "
             "beh./org.: behavioral or organizational difference. Status is assigned mechanically: reproduced (same direction "
             "in both studies), mixed (a mixed direction in either study), not reproduced (A021 direction absent in "
             "R2), not tested (not measured in one or both studies). One execution per arm per study.")
    return (HEADER +
            "\\begin{table}[t]\n\\centering\n\\scriptsize\n\\setlength{\\tabcolsep}{3pt}\n"
            "\\caption{Replication matrix: was the A021 direction repeated in R2?}\n"
            "\\label{tab:replication}\n"
            "\\begin{tabular}{@{}p{0.33\\columnwidth}p{0.22\\columnwidth}p{0.22\\columnwidth}p{0.14\\columnwidth}@{}}\n"
            "\\hline\nOutcome & A021 & R2 & Status \\\\\n\\hline\n"
            f"{body}\n\\hline\n\\end{{tabular}}\n\n"
            f"\\vspace{{2pt}}\\parbox{{\\columnwidth}}{{\\scriptsize {notes}}}\n"
            "\\end{table}\n")


# --------------------------------------------------------------------------
# Macros
# --------------------------------------------------------------------------

def macros(arch: Mapping[str, Any], metrics: Mapping[str, Any]) -> str:
    t = {s: tally(arch, s) for s in STUDIES}
    prefix = {"A021": "ArchA", "R2": "ArchRtwo"}
    reps = replication_rows(arch, metrics)
    status_counts = {s: sum(r.status == s for r in reps) for s in ("reproduced", "mixed", "not reproduced", "not tested")}
    entries = (
        *((f"{prefix[s]}{k[0].upper()}{k[1:]}", word(v), f"{s}: dimensions with direction {k}")
          for s in STUDIES for k, v in t[s].items()),
        ("ArchDimensions", word(len(dimensions(arch))), "rubric dimensions"),
        ("ArchFindings", str(len(arch["findings"])), "coded findings (study x arm x dimension)"),
        ("ArchCitations", str(sum(len(f["evidence"]) for f in arch["findings"])), "code citations verified"),
        ("ArchFalsificationAttempts", word(len(arch["falsification_attempts"])) if len(arch["falsification_attempts"]) <= 10
         else str(len(arch["falsification_attempts"])), "falsification attempts"),
        ("RepReproduced", str(status_counts["reproduced"]), "replication-matrix rows reproduced"),
        ("RepMixed", str(status_counts["mixed"]), "replication-matrix rows mixed"),
        ("RepNotReproduced", str(status_counts["not reproduced"]), "replication-matrix rows not reproduced"),
        ("RepNotTested", str(status_counts["not tested"]), "replication-matrix rows not tested"),
    )
    bad = sorted(n for n, _, _ in entries if not n.isalpha())
    if bad:
        raise ValueError(f"macro names must be letters only: {bad}")
    return HEADER + "\n".join(f"\\newcommand{{\\{n}}}{{{v}}} % {c}" for n, v, c in entries) + "\n"


def render(arch: Mapping[str, Any], metrics: Mapping[str, Any]) -> Mapping[str, str]:
    return MappingProxyType({
        "architecture-matrix.tex": architecture_matrix(arch),
        "replication-matrix.tex": replication_matrix(arch, metrics),
        "architecture-macros.tex": macros(arch, metrics),
    })


# --------------------------------------------------------------------------
# I/O edge
# --------------------------------------------------------------------------

def main(argv: Sequence[str]) -> int:
    files = render(json.loads(ARCH.read_text(encoding="utf-8")), json.loads(METRICS.read_text(encoding="utf-8")))
    if "--check" in argv:
        stale = tuple(n for n, t in sorted(files.items())
                      if not (OUT / n).exists() or (OUT / n).read_text(encoding="utf-8") != t)
        tuple(print(f"STALE manuscript/tables/{n}") for n in stale)
        print("architecture tables up to date" if not stale else f"{len(stale)} table file(s) differ")
        return 1 if stale else 0
    OUT.mkdir(parents=True, exist_ok=True)
    tuple((OUT / n).write_text(t, encoding="utf-8") for n, t in sorted(files.items()))
    print("\n".join(f"manuscript/tables/{n}" for n in sorted(files)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
