#!/usr/bin/env python3
"""Generate the architecture matrix, the recurrence (replication) matrix and architecture macros.

Inputs (read only):
  data/architecture-findings.json  8-dimension rubric applied to both arms of both studies
  data/metrics.json                derived independent/grouped ratios and arm-level counts

Outputs (manuscript/tables/):
  architecture-matrix.tex   D1-D8 x {A021, R2}: grouped/independent category, direction, kind of evidence
  replication-matrix.tex    outcome x {A021, R2} with a recurrence status (direction only)
  architecture-macros.tex   \\newcommand counts used in prose (findings, citations, falsification attempts)

The rubric was written and applied after both studies were unblinded. No dimension tally is produced:
the dimensions are not commensurable, so they are reported by name.

Recurrence status rules (applied mechanically, never typed by hand):
  recurred                    the same non-mixed direction was observed in both studies
  recurred (lower bounds)     same direction, but both operands are lower bounds (not counted as evidence)
  mixed in both               the direction is mixed in both studies
  did not recur               A021 showed a direction that R2 did not show
  not comparable              measured, but not with a comparable definition in both studies
  not tested                  not measured in either study

Deterministic output; stdlib only. No p-values, intervals or cross-study means.

Usage: python3 scripts/build_architecture_table.py [--check]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from types import MappingProxyType
from typing import Any, Mapping, NamedTuple, Optional, Sequence

PKG = Path(__file__).resolve().parent.parent
ARCH = PKG / "data" / "architecture-findings.json"
METRICS = PKG / "data" / "metrics.json"
OUT = PKG / "manuscript" / "tables"

HEADER = ("% Generated by scripts/build_architecture_table.py from data/architecture-findings.json "
          "and data/metrics.json. Do not edit.\n")

STUDIES = ("A021", "R2")
W = "agg:workers"
ARM = "agg:arm"

CATEGORY_ABBR: Mapping[str, str] = MappingProxyType({
    "unified": "U", "duplicated-compatible": "DC", "divergent": "Dv",
    "missing": "Mi", "not-assessable": "NA"})

DIRECTION_ABBR: Mapping[str, str] = MappingProxyType({
    "grouped_more_unified": "G", "independent_more_unified": "I",
    "equivalent": "eq", "mixed": "mixed", "not_assessable": "NA"})

SHORT_NAMES: Mapping[str, str] = MappingProxyType({
    "D1": "Persistence/store model",
    "D2": "Member admission (create vs.\\ add)",
    "D3": "Member classification (show vs.\\ checkpoint)",
    "D4": "Checkpoint ownership validation",
    "D5": "Error/JSON/exit contract",
    "D6": "Mutation/concurrency model",
    "D7": "Shared abstractions and baseline-rule reuse",
    "D8": "Duplicate definitions inside the feature"})

# Construct split requested by review: cross-item consistency vs. per-verb correctness and reuse.
CONSISTENCY_DIMS = ("D1", "D2", "D3", "D5", "D6", "D8")
CORRECTNESS_DIMS = ("D4", "D7")

# Behavioral differences backed by a runtime probe in the audit (architecture-findings.md, probe table:
# P2 -> D2/D7, P4/P6/P7 -> D5, concurrent create -> D6). Other behavioral codes rest on code reading.
PROBED_DIMS = frozenset({"D2", "D5", "D6", "D7"})



# --------------------------------------------------------------------------
# Pure helpers
# --------------------------------------------------------------------------

def comparisons(arch: Mapping[str, Any]) -> Mapping[tuple[str, str], Mapping[str, Any]]:
    return MappingProxyType({(c["study"], c["dimension"]): c for c in arch["comparisons"]})


def stale_sensitive(arch: Mapping[str, Any]) -> frozenset[tuple[str, str, str]]:
    """(study, dimension, arm) whose finding depends on a stale-start item."""
    arm_of = {i["id"]: i["arm"] for i in arch["implementations"]}
    return frozenset((f["study"], f["dimension"], arm_of[f["implementation"]])
                     for f in arch["findings"] if f["stale_start_sensitive"] is True)


def dimensions(arch: Mapping[str, Any]) -> tuple[str, ...]:
    return tuple(d["id"] for d in arch["rubric"]["dimensions"])


def word(n: int) -> str:
    return ("zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten")[n] if 0 <= n <= 10 else str(n)


# --------------------------------------------------------------------------
# Architecture matrix
# --------------------------------------------------------------------------

def arch_cells(cmp_: Mapping[str, Any], stale: frozenset, study: str, dim: str) -> str:
    def mark(arm: str) -> str:
        return "$^{\\dagger}$" if (study, dim, arm) in stale else ""
    g = CATEGORY_ABBR[cmp_["grouped_category"]] + mark("grouped")
    i = CATEGORY_ABBR[cmp_["independent_category"]] + mark("independent")
    kind = ("" if not cmp_["behavioral_difference"] else "$^{p}$" if dim in PROBED_DIMS else "$^{c}$")
    return f"{g}/{i} & {DIRECTION_ABBR[cmp_['direction']]}{kind}"


def architecture_matrix(arch: Mapping[str, Any]) -> str:
    cs, stale = comparisons(arch), stale_sensitive(arch)
    def block(title: str, dims: Sequence[str]) -> str:
        return (f"\\multicolumn{{5}}{{@{{}}l}}{{\\textit{{{title}}}}} \\\\\n" +
                "\n".join(f"{dim} {SHORT_NAMES[dim]} & " +
                          " & ".join(arch_cells(cs[(s, dim)], stale, s, dim) for s in STUDIES) + " \\\\"
                          for dim in dims))
    rows = block("Cross-item consistency", CONSISTENCY_DIMS) + "\n" + block("Per-verb correctness and reuse", CORRECTNESS_DIMS)
    notes = ("Cells: grouped/independent category. U unified; DC duplicated-compatible; Dv divergent; Mi missing. "
             "Direction: G or I, the arm whose verbs agree more (consistency rows) or that meets the rule "
             "(correctness rows); eq equivalent. Behavioral difference shown by a runtime probe ($^{p}$) or "
             "by code reading only ($^{c}$); no mark: organization only. $^{\\dagger}$: comes from an item "
             "whose session started from a stale checkout. Unified means consistent across verbs, not correct: "
             "the grouped arms' shared admission rule ignores the planner's external-repository inference (probe "
             "P2, add), and at create every arm accepts such an item (P3). Rubric written and applied after unblinding by one AI auditor; no second coder.")
    return (HEADER +
            "\\begin{table}[t]\n\\centering\n\\scriptsize\n\\setlength{\\tabcolsep}{3pt}\n"
            "\\caption{Post hoc architecture rubric: category per arm and direction per study}\n"
            "\\label{tab:architecture}\n"
            "\\begin{tabular}{@{}p{0.44\\columnwidth}cccc@{}}\n\\hline\n"
            " & \\multicolumn{2}{c}{A021} & \\multicolumn{2}{c}{R2} \\\\\n"
            "Dimension & G/I & Dir. & G/I & Dir. \\\\\n\\hline\n"
            f"{rows}\n\\hline\n\\end{{tabular}}\n\n"
            f"\\vspace{{2pt}}\\parbox{{\\columnwidth}}{{\\scriptsize {notes}}}\n"
            "\\end{table}\n")


# --------------------------------------------------------------------------
# Recurrence matrix
# --------------------------------------------------------------------------

class Rep(NamedTuple):
    family: str
    outcome: str
    a021: str
    r2: str
    status: str


def derived_index(metrics: Mapping[str, Any]) -> Mapping[tuple[str, str, str], Mapping[str, Any]]:
    return MappingProxyType({(d["study"], d["unit"], d["metric"]): d for d in metrics["derived"]})


def row_index(metrics: Mapping[str, Any]) -> Mapping[tuple[str, str, str, str], Mapping[str, Any]]:
    return MappingProxyType({(r["study"], r["arm"], r["unit"], r["metric"]): r for r in metrics["rows"]})


def status_from(a: Optional[str], b: Optional[str]) -> str:
    if a is None and b is None:
        return "not tested"
    if a is None or b is None:
        return "not comparable"
    if a == "mixed" and b == "mixed":
        return "mixed in both"
    return "recurred" if a == b else "did not recur"


def resource_rep(dix: Mapping, label: str, metric: str) -> Rep:
    def cell(study: str) -> tuple[Optional[str], str]:
        d = dix.get((study, W, metric))
        if d is None or d["ratio_independent_over_grouped"] is None:
            return None, "n/a"
        red = d["reduction_grouped_vs_independent"]
        direction = "G lower" if red > 0 else "I lower" if red < 0 else "equal"
        return direction, f"{direction}, I/G {d['ratio_independent_over_grouped']:.1f}"
    (da, ca), (db, cb) = cell("A021"), cell("R2")
    return Rep("Resources (worker-only)", label, ca, cb, status_from(da, db))


def lower_bound_rep(rix: Mapping, label: str, metric: str) -> Rep:
    def cell(study: str) -> tuple[Optional[str], str]:
        g = rix.get((study, "grouped", W, metric))
        i = rix.get((study, "independent", W, metric))
        if g is None or i is None or g["value"] is None or i["value"] is None:
            return None, "n/a"
        direction = "G fewer" if g["value"] < i["value"] else "I fewer" if i["value"] < g["value"] else "equal"
        return direction, f"{direction} ($\\geq${int(g['value'])} vs.\\ $\\geq${int(i['value'])})"
    (da, ca), (db, cb) = cell("A021"), cell("R2")
    status = status_from(da, db)
    return Rep("Repeated context (lower bounds)", label, ca, cb,
               "same direction, lower bounds only" if status == "recurred" else status)


def arch_rep(cs: Mapping, dim: str) -> Rep:
    def direction(study: str) -> Optional[str]:
        c = cs.get((study, dim))
        return None if c is None else DIRECTION_ABBR[c["direction"]]
    def cell(study: str) -> str:
        c = cs.get((study, dim))
        if c is None:
            return "n/a"
        d = DIRECTION_ABBR[c["direction"]]
        text = {"eq": "equivalent"}.get(d, d)
        return text + (", beh." if c["behavioral_difference"] else ", org." if d in ("G", "I") else "")
    family = "Architecture: consistency" if dim in CONSISTENCY_DIMS else "Architecture: correctness/reuse"
    status = status_from(direction("A021"), direction("R2"))
    return Rep(family, f"{dim} {SHORT_NAMES[dim]}", cell("A021"), cell("R2"),
               status + "$^{a}$" if status in ("recurred", "mixed in both") else status)


def lc_rep(arch: Mapping[str, Any], label: str, ids: Sequence[str], arm: str) -> Rep:
    impls = frozenset(i for lc in arch["local_correctness"] if lc["id"] in ids for i in lc["implementations"])
    seen = {s: f"{s}-{arm}" in impls for s in STUDIES}
    cell = {s: ("observed" if seen[s] else "not observed") for s in STUDIES}
    status = "recurred" if all(seen.values()) else ("did not recur" if seen["A021"] else "not tested")
    return Rep("Local correctness", label, cell["A021"], cell["R2"], status)


def count_rep(rix: Mapping, label: str, metric: str) -> Rep:
    def pair(study: str) -> Optional[tuple[int, int]]:
        g = rix.get((study, "grouped", ARM, metric))
        i = rix.get((study, "independent", ARM, metric))
        if g is None or i is None or g["value"] is None or i["value"] is None:
            return None
        return int(g["value"]), int(i["value"])
    def direction(p: Optional[tuple[int, int]]) -> Optional[str]:
        return None if p is None else ("I more" if p[1] > p[0] else "G more" if p[0] > p[1] else "tie")
    def cell(p: Optional[tuple[int, int]]) -> str:
        return "no comparable tally" if p is None else f"{direction(p)} ({p[0]} vs.\\ {p[1]})"
    pa, pb = pair("A021"), pair("R2")
    return Rep("Local correctness", label, cell(pa), cell(pb), status_from(direction(pa), direction(pb)))


NOT_TESTED: tuple[tuple[str, str], ...] = (
    ("Generalization", "Other repository or feature family"),
    ("Generalization", "Low-affinity cohort (planned study blocked)"),
    ("Generalization", "Other implementing models or runtimes"),
    ("Generalization", "Larger cohorts / context pressure"),
    ("Mechanism", "Retained context vs.\\ mandated analysis separated"),
)


def replication_rows(arch: Mapping[str, Any], metrics: Mapping[str, Any]) -> tuple[Rep, ...]:
    dix, rix, cs = derived_index(metrics), row_index(metrics), comparisons(arch)
    resources = (
        resource_rep(dix, "Platform cost", "cost_usd_platform"),
        resource_rep(dix, "Summed active session time", "active_session_sum_s"),
        resource_rep(dix, "Output tokens", "output_tokens_platform"),
        resource_rep(dix, "Cache-read tokens", "cache_read_tokens_platform"),
    )
    repeated = (
        lower_bound_rep(rix, "Model requests", "model_requests_transcript"),
        lower_bound_rep(rix, "File reads", "file_reads_transcript"),
        lower_bound_rep(rix, "Searches", "searches_transcript"),
    )
    architecture = tuple(arch_rep(cs, dim) for dim in (*CONSISTENCY_DIMS, *CORRECTNESS_DIMS))
    local = (
        count_rep(rix, "Net tests added vs.\\ baseline (count, not quality)", "fsharp_tests_net_added"),
        count_rep(rix, "Confirmed acceptance defects", "confirmed_acceptance_defects_r2"),
    )
    untested = tuple(Rep(f, o, "--", "--", "not tested") for f, o in NOT_TESTED)
    return resources + repeated + architecture + local + untested


def replication_matrix(arch: Mapping[str, Any], metrics: Mapping[str, Any]) -> str:
    reps = replication_rows(arch, metrics)
    families = tuple(dict.fromkeys(r.family for r in reps))
    body = "\n".join(
        f"\\multicolumn{{4}}{{@{{}}l}}{{\\textit{{{fam}}}}} \\\\\n" +
        "\n".join(f"{r.outcome} & {r.a021} & {r.r2} & {r.status} \\\\" for r in reps if r.family == fam)
        for fam in families)
    notes = ("G grouped; I independent. Direction only: a recurred direction in two correlated single "
             "executions of one setup is not a replication of an effect size. Resource rows: worker-only "
             "platform figures, I/G ratio to one decimal. Repeated-context rows: both arms' script counts are "
             "lower bounds, so the direction is listed but not counted as recurred evidence. Architecture rows: "
             "the arm favored in Table~\\ref{tab:architecture}; beh./org.: behavioral or organizational "
             "difference; $^{a}$: R2's grouped analysis had headings anticipating these dimensions and R2's "
             "designer knew A021's results, so these recurrences carry little independent weight. Lost updates "
             "and lock-contention failures are part of D6; blank-decision handling (stored verbatim in A021, "
             "silently dropped in R2) is part of D4. Not comparable: measured in R2 "
             "but with no comparable A021 tally.")
    return (HEADER +
            "\\begin{table}[t]\n\\centering\n\\scriptsize\n\\setlength{\\tabcolsep}{3pt}\n"
            "\\caption{Recurrence matrix: did the A021 direction recur in the R2 re-execution?}\n"
            "\\label{tab:replication}\n"
            "\\begin{tabular}{@{}p{0.31\\columnwidth}p{0.23\\columnwidth}p{0.23\\columnwidth}p{0.15\\columnwidth}@{}}\n"
            "\\hline\nOutcome & A021 & R2 & Status \\\\\n\\hline\n"
            f"{body}\n\\hline\n\\end{{tabular}}\n\n"
            f"\\vspace{{2pt}}\\parbox{{\\columnwidth}}{{\\scriptsize {notes}}}\n"
            "\\end{table}\n")


# --------------------------------------------------------------------------
# Macros
# --------------------------------------------------------------------------

def macros(arch: Mapping[str, Any]) -> str:
    n_fals = len(arch["falsification_attempts"])
    cs = comparisons(arch)
    words = {"grouped_more_unified": "in favor of the cohort arm", "independent_more_unified": "in favor of the per-item arm",
             "mixed": "mixed", "equivalent": "equivalent", "not_assessable": "not assessable"}
    entries = (
        ("ArchDSevenA", words[cs[("A021", "D7")]["direction"]], "A021 D7 direction"),
        ("ArchDSevenRtwo", words[cs[("R2", "D7")]["direction"]], "R2 D7 direction"),
        ("ArchDimensions", word(len(dimensions(arch))), "rubric dimensions"),
        ("ArchFindings", str(len(arch["findings"])), "coded findings (study x arm x dimension)"),
        ("ArchCitations", str(sum(len(f["evidence"]) for f in arch["findings"])), "code citations verified"),
        ("ArchFalsificationAttempts", word(n_fals) if n_fals <= 10 else str(n_fals), "falsification attempts"),
    )
    bad = sorted(n for n, _, _ in entries if not n.isalpha())
    if bad:
        raise ValueError(f"macro names must be letters only: {bad}")
    return HEADER + "\n".join(f"\\newcommand{{\\{n}}}{{{v}}} % {c}" for n, v, c in entries) + "\n"


def render(arch: Mapping[str, Any], metrics: Mapping[str, Any]) -> Mapping[str, str]:
    return MappingProxyType({
        "architecture-matrix.tex": architecture_matrix(arch),
        "replication-matrix.tex": replication_matrix(arch, metrics),
        "architecture-macros.tex": macros(arch),
    })


# --------------------------------------------------------------------------
# I/O edge
# --------------------------------------------------------------------------

def main(argv: Sequence[str]) -> int:
    files = render(json.loads(ARCH.read_text(encoding="utf-8")), json.loads(METRICS.read_text(encoding="utf-8")))
    if "--check" in argv:
        stale = tuple(n for n, t in sorted(files.items())
                      if not (OUT / n).exists() or (OUT / n).read_text(encoding="utf-8") != t)
        tuple(print(f"STALE manuscript/tables/{n}") for n in stale)
        print("architecture tables up to date" if not stale else f"{len(stale)} table file(s) differ")
        return 1 if stale else 0
    OUT.mkdir(parents=True, exist_ok=True)
    tuple((OUT / n).write_text(t, encoding="utf-8") for n, t in sorted(files.items()))
    print("\n".join(f"manuscript/tables/{n}" for n in sorted(files)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
