<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Ros.Integration.Compatibility.Tests</AssemblyName>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Ros.Integration/Ros.Integration.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="TestFramework.fs" />
    <Compile Include="CompatibilityTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
